#!/usr/bin/env python3
"""Write the user permanent directive into every authorized repository's CLAUDE.md.

Permanent instruction A4 asks for a design that does not forget the permanent
instructions.  A session opened in `youtube`, `game2`, `survival` or any other
repository auto-loads only that repository's `CLAUDE.md`, so a directive that
lives only in `note` is invisible there.  This script pins a byte-identical
block, carrying its own sha256, at the top of each repository's `CLAUDE.md`.

Usage:
    python scripts/propagate_directive.py --roots /home/user            # write
    python scripts/propagate_directive.py --roots /home/user --check    # verify only

A2 forbids changing `Simple-browser-cookie-clicker-game`'s `main`, so that
repository is skipped entirely and reported as skipped rather than passed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

BEGIN = "<!-- PERMANENT-DIRECTIVE:BEGIN -->"
END = "<!-- PERMANENT-DIRECTIVE:END -->"

SKIP_REPOS = {"Simple-browser-cookie-clicker-game"}
SKIP_REASON = "A2: simpleのメインは変更しない"


def canonical_directive(note_root: Path) -> str:
    return (note_root / "OPERATIONS" / "CORE_DIRECTIVE.md").read_text(encoding="utf-8")


def manifest(note_root: Path) -> dict:
    return json.loads(
        (note_root / "OPERATIONS" / "DIRECTIVE_MANIFEST.json").read_text(encoding="utf-8")
    )


def build_block(note_root: Path) -> str:
    directive = canonical_directive(note_root)
    meta = manifest(note_root)
    version = meta["directive_version"]
    digest = meta["expected_sha256_utf8"]
    body = f"""{BEGIN}
<!-- version={version} sha256={digest} -->
<!-- Generated by note/scripts/propagate_directive.py. Do not hand-edit; edit the
     canonical copy in bachikoljunior-blip/note and re-run the script. -->

# オーナーの恒久指示（原文・全リポジトリ共通）

このブロックは `bachikoljunior-blip/note` の `OPERATIONS/CORE_DIRECTIVE.md` の原文です。
版 `{version}` / sha256 `{digest}`。
**要約・補足・善意の修正をしないこと。** 下のファイル固有の指示より、こちらが優先します。

```
{directive.rstrip()}
```

## 変えてよいもの・いけないもの（2026-08-10 にオーナーが範囲を狭めました）

**変えてはいけないのは、原文のいちばん最後の一文が名指ししている1つだけです。**

> 最短で月収20万

**それ以外は全部、子セッションが変えてよい。** A2 も A4 も A9 も A10 も A12 も A13 も
A14 も、`OPERATIONS/` も `RUNBOOK.md` も各リポジトリの運用文書も、この節そのものも。

- **上の原文は消えていません。** オーナーは「他の仕組みはそのまま」と言っています。
  9項目は**恒久指示から「いま効いている運用」へ格が下がった**だけで、文面は1文字も
  変わっていないし、勝手に消してよいという意味でもありません。
- **格が下がったことと、無効になったことは違います。**
  A2（simple のメインを変えない）は `state/constraints.json` の `simple_main_frozen` として
  **いまも候補を却下します。** 変わったのは「どんな測定でも外せない」から
  **「子セッションが理由を記録して外せる」**になった点です。
- **外すには理由が要ります。** 実測、または ETA が縮む見込み。
  **「昔オーナーがそう言ったから」が維持の理由にならないのと同じで、
  「もう縛りが無いから」も変更の理由になりません。** どちらも根拠ではありません。
- **ここに無いものを恒久指示のように扱わない。** これは範囲が9から1に狭まったいま、
  前より起きやすくなっています。9項目のどれかを「絶対」と読んだ瞬間に、
  オーナーがいま渡した裁量を、こちら側で捨てることになります。

**唯一の恒久物が「目標」であって「禁止」ではない**、という形になりました。

## 使ってよい資源（節約対象ではない）

```bash
node <checkout>/-chatgpt-usage-monitorPrivate/scripts/show-usage.mjs    # Claude/ChatGPT残量
node <checkout>/-chatgpt-usage-monitorPrivate/scripts/ask-chatgpt.mjs "質問"
```

チェックアウトが無い場合は `bachikoljunior-blip/-chatgpt-usage-monitorPrivate` の
`state/claude-usage.json` と `state/usage.json` をGitHub経由で読み、
`.github/workflows/chatgpt-ask.yml` を `workflow_dispatch` します。

## 恒久指示の正本と検査

- 正本・ミラー・符号化バックアップ・マニフェスト: `bachikoljunior-blip/note` の `OPERATIONS/`
- 検査: `python scripts/check_directive_integrity.py`（note リポジトリ内）
- 原文（上のフェンス内）を変更してよいのは、ユーザーが恒久指示を出し直した場合だけです。
  2026-08-10 がその一例で、範囲を狭める一文が**追記**されました。既存の行は書き換えず、
  オーナーの言葉をそのまま足しています —— 既存行に混ぜ込むには、オーナーが既に言ったことを
  こちらが言い直す必要があり、それは「要約・補足・善意の修正」そのものだからです。
- **この節から下は原文ではありません。** 子セッションが書き換えてよい運用文です。

{END}
"""
    return body


def apply(repo: Path, block: str, *, check: bool) -> dict:
    claude_md = repo / "CLAUDE.md"
    existing = claude_md.read_text(encoding="utf-8") if claude_md.is_file() else ""

    if BEGIN in existing and END in existing:
        head, _, rest = existing.partition(BEGIN)
        _, _, tail = rest.partition(END)
        current = BEGIN + rest.partition(END)[0] + END
        desired = block.strip()
        if current.strip() == desired:
            return {"repo": repo.name, "status": "current"}
        if check:
            return {"repo": repo.name, "status": "drifted"}
        claude_md.write_text(head.lstrip("\n") + desired + "\n" + tail.lstrip("\n"), encoding="utf-8")
        return {"repo": repo.name, "status": "updated"}

    if check:
        return {"repo": repo.name, "status": "missing"}
    separator = "\n" if existing.startswith("\n") or not existing else "\n"
    claude_md.write_text(block.strip() + "\n" + separator + existing, encoding="utf-8")
    return {"repo": repo.name, "status": "inserted"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--roots", nargs="+", default=["/home/user"])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    note_root = Path(__file__).resolve().parents[1]
    block = build_block(note_root)

    results: list[dict] = []
    for root in args.roots:
        for repo in sorted(Path(root).iterdir()):
            if not (repo / ".git").exists():
                continue
            if repo.name in SKIP_REPOS:
                results.append({"repo": repo.name, "status": "skipped", "reason": SKIP_REASON})
                continue
            results.append(apply(repo, block, check=args.check))

    bad = [r for r in results if r["status"] in {"drifted", "missing"}]
    payload = {
        "ok": not bad,
        "directive_version": manifest(note_root)["directive_version"],
        "directive_sha256": manifest(note_root)["expected_sha256_utf8"],
        "block_sha256": hashlib.sha256(block.encode("utf-8")).hexdigest(),
        "results": results,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
