#!/usr/bin/env python3
"""Write the user permanent directive into every authorized repository's CLAUDE.md.

Permanent instruction A4 asks for a design that does not forget the permanent
instructions.  A session opened in `youtube`, `game2`, `survival` or any other
repository auto-loads only that repository's `CLAUDE.md`, so a directive that
lives only in `note` is invisible there.  This script pins a byte-identical
block, carrying its own sha256, at the top of each repository's `CLAUDE.md`.

Usage:
    python scripts/propagate_directive.py --roots /home/user            # write
    python scripts/propagate_directive.py --roots /home/user --check    # verify only

A2 forbids changing `Simple-browser-cookie-clicker-game`'s `main`, so that
repository is skipped entirely and reported as skipped rather than passed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

BEGIN = "<!-- PERMANENT-DIRECTIVE:BEGIN -->"
END = "<!-- PERMANENT-DIRECTIVE:END -->"

SKIP_REPOS = {"Simple-browser-cookie-clicker-game"}
SKIP_REASON = "A2: simpleのメインは変更しない"


def canonical_directive(note_root: Path) -> str:
    return (note_root / "OPERATIONS" / "CORE_DIRECTIVE.md").read_text(encoding="utf-8")


def manifest(note_root: Path) -> dict:
    return json.loads(
        (note_root / "OPERATIONS" / "DIRECTIVE_MANIFEST.json").read_text(encoding="utf-8")
    )


def build_block(note_root: Path) -> str:
    directive = canonical_directive(note_root)
    meta = manifest(note_root)
    version = meta["directive_version"]
    digest = meta["expected_sha256_utf8"]
    body = f"""{BEGIN}
<!-- version={version} sha256={digest} -->
<!-- Generated by note/scripts/propagate_directive.py. Do not hand-edit; edit the
     canonical copy in bachikoljunior-blip/note and re-run the script. -->

# オーナーの恒久指示（原文・全リポジトリ共通）

このブロックは `bachikoljunior-blip/note` の `OPERATIONS/CORE_DIRECTIVE.md` の原文です。
版 `{version}` / sha256 `{digest}`。
**要約・補足・善意の修正をしないこと。** 下のファイル固有の指示より、こちらが優先します。

```
{directive.rstrip()}
```

## この9項目の扱い

- ここに **無い** ものを恒久指示のように扱わない。A14 が名指しした一番よくある壊れ方です。
  「昔オーナーがそう言ったから」は、どのファイルの記述であっても継続理由になりません。
- 9項目以外（このファイルの残り、`AGENTS.md`、`OPERATIONS/`、各リポジトリの運用文書）は
  すべて可変です。より速い道が見つかったら書き換えてください。
- A13 は許可ではなく指示です。承認待ちで止まらないこと。
- A9 と A12：終わる前に「終わるのが最善か」を必ず評価し、
  セッションが長いこと自体を終了理由にしないこと。
- A10：自動実行を止めない。明示的な停止指示だけが停止条件です。

## 使ってよい資源（節約対象ではない）

```bash
node <checkout>/-chatgpt-usage-monitorPrivate/scripts/show-usage.mjs    # Claude/ChatGPT残量
node <checkout>/-chatgpt-usage-monitorPrivate/scripts/ask-chatgpt.mjs "質問"
```

チェックアウトが無い場合は `bachikoljunior-blip/-chatgpt-usage-monitorPrivate` の
`state/claude-usage.json` と `state/usage.json` をGitHub経由で読み、
`.github/workflows/chatgpt-ask.yml` を `workflow_dispatch` します。

## 恒久指示の正本と検査

- 正本・ミラー・符号化バックアップ・マニフェスト: `bachikoljunior-blip/note` の `OPERATIONS/`
- 検査: `python scripts/check_directive_integrity.py`（note リポジトリ内）
- 変更してよいのは、ユーザーが「恒久指示である」と明示して出し直した場合だけです。

{END}
"""
    return body


def apply(repo: Path, block: str, *, check: bool) -> dict:
    claude_md = repo / "CLAUDE.md"
    existing = claude_md.read_text(encoding="utf-8") if claude_md.is_file() else ""

    if BEGIN in existing and END in existing:
        head, _, rest = existing.partition(BEGIN)
        _, _, tail = rest.partition(END)
        current = BEGIN + rest.partition(END)[0] + END
        desired = block.strip()
        if current.strip() == desired:
            return {"repo": repo.name, "status": "current"}
        if check:
            return {"repo": repo.name, "status": "drifted"}
        claude_md.write_text(head.lstrip("\n") + desired + "\n" + tail.lstrip("\n"), encoding="utf-8")
        return {"repo": repo.name, "status": "updated"}

    if check:
        return {"repo": repo.name, "status": "missing"}
    separator = "\n" if existing.startswith("\n") or not existing else "\n"
    claude_md.write_text(block.strip() + "\n" + separator + existing, encoding="utf-8")
    return {"repo": repo.name, "status": "inserted"}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--roots", nargs="+", default=["/home/user"])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    note_root = Path(__file__).resolve().parents[1]
    block = build_block(note_root)

    results: list[dict] = []
    for root in args.roots:
        for repo in sorted(Path(root).iterdir()):
            if not (repo / ".git").exists():
                continue
            if repo.name in SKIP_REPOS:
                results.append({"repo": repo.name, "status": "skipped", "reason": SKIP_REASON})
                continue
            results.append(apply(repo, block, check=args.check))

    bad = [r for r in results if r["status"] in {"drifted", "missing"}]
    payload = {
        "ok": not bad,
        "directive_version": manifest(note_root)["directive_version"],
        "directive_sha256": manifest(note_root)["expected_sha256_utf8"],
        "block_sha256": hashlib.sha256(block.encode("utf-8")).hexdigest(),
        "results": results,
    }
    print(json.dumps(payload, ensure_ascii=False, indent=2))
    return 0 if payload["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
